name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '2.2'  # Use Gradle 2.2 as required

      - name: Download Dependencies
        run: gradle build --no-daemon

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
